version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
  server:
    container_name: server
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
